# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qrgen < Formula
  desc "A terminal-based QR code generator with an interactive TUI"
  homepage "https://github.com/DalyChouikh/qr-code-generator"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DalyChouikh/qr-code-generator/releases/download/v1.0.4/qrgen_1.0.4_darwin_amd64.tar.gz"
      sha256 "16dba66ee32e4220b6adf82b8ffef5bd9d21805f4a2f66db5195f5fd7a93a192"

      def install
        bin.install "qrgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DalyChouikh/qr-code-generator/releases/download/v1.0.4/qrgen_1.0.4_darwin_arm64.tar.gz"
      sha256 "ca8791a2ad5368ea4aabec74af5615b6a757f55c6d4e873bbe8dee07b68f8a8b"

      def install
        bin.install "qrgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DalyChouikh/qr-code-generator/releases/download/v1.0.4/qrgen_1.0.4_linux_amd64.tar.gz"
      sha256 "5295541488da223824603344829c7965d4b3aaa5dcda8a88e3020f6fcca0affb"
      def install
        bin.install "qrgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DalyChouikh/qr-code-generator/releases/download/v1.0.4/qrgen_1.0.4_linux_arm64.tar.gz"
      sha256 "153f0e53fa885caaf4abdbf4dd4572c48dfd1a56bf401d9b0ffd9994c5340368"
      def install
        bin.install "qrgen"
      end
    end
  end

  test do
    system "#{bin}/qrgen", "--version"
  end
end
